//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusTbl
    {
        public int CampusID { get; set; }
        public string CampusName { get; set; }
        public string Location { get; set; }
        public Nullable<int> UniID { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual UniversityTbl UniversityTbl { get; set; }
    }
}
