//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigntbl
    {
        public int CampID { get; set; }
        public string CampRequestID { get; set; }
        public Nullable<int> UniID { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public string UniDepartment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Image { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> userid { get; set; }
        public string CampSession { get; set; }
        public Nullable<int> TradeID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string SessionYear { get; set; }
    
        public virtual UniversityTbl UniversityTbl { get; set; }
    }
}
