//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Uni_Find_DB_310324Entities : DbContext
    {
        public Uni_Find_DB_310324Entities()
            : base("name=Uni_Find_DB_310324Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationManagement> ApplicationManagements { get; set; }
        public virtual DbSet<FormStatu> FormStatus { get; set; }
        public virtual DbSet<PaymentToUni> PaymentToUnis { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<RegisterTbl> RegisterTbls { get; set; }
        public virtual DbSet<Reporting> Reportings { get; set; }
        public virtual DbSet<SaleTbl> SaleTbls { get; set; }
        public virtual DbSet<UniversityTbl> UniversityTbls { get; set; }
        public virtual DbSet<CampusTbl> CampusTbls { get; set; }
        public virtual DbSet<ProgramTbl> ProgramTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tradetbl> Tradetbls { get; set; }
        public virtual DbSet<StudentAdmissionForm> StudentAdmissionForms { get; set; }
        public virtual DbSet<Campaigntbl> Campaigntbls { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PaymentByStudent> PaymentByStudents { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
    
        public virtual ObjectResult<StudentAdmissionReport_Result> StudentAdmissionReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentAdmissionReport_Result>("StudentAdmissionReport");
        }
    
        public virtual ObjectResult<UniversityReport_Result> UniversityReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UniversityReport_Result>("UniversityReport");
        }
    }
}
