//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentByStudent
    {
        public int TransID { get; set; }
        public Nullable<int> StdID { get; set; }
        public string FormCode { get; set; }
        public Nullable<int> ApttCharges { get; set; }
        public Nullable<int> ServiceCharges { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string PaymentOption { get; set; }
        public string Program { get; set; }
        public string Uni { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Status { get; set; }
        public string Remarks { get; set; }
    }
}
