//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterTbl
    {
        public int StdID { get; set; }
        public string StdCode { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string CNIC { get; set; }
        public string Qualification { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Type { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
