//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporting
    {
        public int ID { get; set; }
        public Nullable<int> TotalStudent { get; set; }
        public Nullable<int> EnrolledStudent { get; set; }
        public Nullable<int> ActiveStudent { get; set; }
        public Nullable<int> OffStudent { get; set; }
    }
}
