//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTbl
    {
        public int SaleID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> ApttCharges { get; set; }
        public Nullable<int> ServiceCharges { get; set; }
        public Nullable<int> TotalSale { get; set; }
        public Nullable<int> NetIncome { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
