//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdmissionForm
    {
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string FormID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Policy { get; set; }
        public string Qualification { get; set; }
        public string UniID { get; set; }
        public string ProgramID { get; set; }
        public string DegreeID { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PaymentStatus { get; set; }
        public string CNIC { get; set; }
    }
}
