//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tradetbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tradetbl()
        {
            this.ProgramTbls = new HashSet<ProgramTbl>();
        }
    
        public int ID { get; set; }
        public string TradeName { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<int> UniID { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramTbl> ProgramTbls { get; set; }
        public virtual UniversityTbl UniversityTbl { get; set; }
    }
}
